# This is a basic workflow to help you get started with Actions

name: CI-deploy-github-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  build-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Setting default directory to run commands
    defaults:
      run:
        shell: bash # not compulsory
        working-directory: ./guess-number-game-app

    permissions:
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout to github runner
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying guess-number-game-app to GitHub Pages

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      #- name: cd into app folder
       # run: cd ./guess-number-game-app/

      - name: Install dependencies and build
        # Defining the directory to run commands in this step
        # working-directory: ./guess-number-game-app
        run: |
          pwd
          npm ci
          npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  # deploy-app:
  #   needs: build-app
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write

  #   defaults:
  #     run:
  #       working-directory: ./guess-number-game-app

  #   steps:
  #     - name: Deploy to GitHub Pages
  #       uses: actions/deploy-pages@v4

